node_paypal_payment.settings:
  type: config_object
  label: 'Node paypal payment config'
  mapping:
    npp_on:
      type: boolean
      label: 'Allow paypal payment on node creation'
    npp_email:
      type: email
      label: 'Paypal Email-Id'
    npp_amt:
      type: float
      label: 'Fee'
